name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        gomplate-version: [latest]
        # gomplate-version: [latest, v3.9.0, v3.8.0]
        # os: [macos-latest, windows-latest, ubuntu-latest]
        # version: [1.1.0, 1.0.0]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gomplate
      uses: ./
      with:
        gomplate-version: ${{ matrix.gomplate-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Capture gomplate version installed
      run: |
        export GOMPLATE_VERSION=$( gh --version )
        echo 'GOMPLATE_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
        gomplate --version >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Verify
      shell: python
      env:
        GH_VERSION_EXPECTED: ${{ matrix.gomplate-version }}
      run: |
        import sys, os
        sys.exit(
            int(not os.environ["GH_VERSION_EXPECTED"] in os.environ["GH_VERSION_INSTALLED"])
        )
